export const shellCopy = {
  de: {
    skip: "Zum Inhalt springen",
    local: "Fortschritt bleibt auf diesem Gerät",
    academyNav: "Academy-Navigation",
    primary: "Hauptnavigation",
    details: "Lerndetails",
    expand: "Seitenleiste ausklappen",
    collapse: "Seitenleiste einklappen",
    compact: "Kompakt",
    mobile: "Mobile Hauptnavigation",
    close: "Schließen",
  },
  sl: {
    skip: "Preskoči na vsebino",
    local: "Napredek ostane v tej napravi",
    academyNav: "Navigacija Akademije",
    primary: "Glavna navigacija",
    details: "Podrobnosti učenja",
    expand: "Razširi stransko vrstico",
    collapse: "Strni stransko vrstico",
    compact: "Strnjeno",
    mobile: "Glavna mobilna navigacija",
    close: "Zapri",
  },
  en: {
    skip: "Skip to content",
    local: "Progress stays on this device",
    academyNav: "Academy navigation",
    primary: "Primary navigation",
    details: "Learning details",
    expand: "Expand sidebar",
    collapse: "Collapse sidebar",
    compact: "Compact",
    mobile: "Mobile primary navigation",
    close: "Close",
  },
};
