import sys
from pathlib import Path

from sqlalchemy import engine_from_config, pool

from alembic import context

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import app.models  # noqa: F401
from app.core.config import get_settings
from app.database import Base

config = context.config
raw_url = str(config.attributes.get("database_url") or get_settings().alembic_database_url)
config.set_main_option("sqlalchemy.url", raw_url.replace("%", "%%"))
target_metadata = Base.metadata

# Historical news tables remain in existing databases by design. They are no
# longer active ORM models and must never appear as autogenerated drops.
LEGACY_NEWS_TABLES = frozenset(
    {
        "articles",
        "article_tickers",
        "backfill_checkpoints",
        "ingestion_locks",
        "ingestion_jobs",
        "service_heartbeats",
        "ingestion_runs",
    }
)


def include_object(_object, name, type_, _reflected, _compare_to):
    return not (type_ == "table" and name in LEGACY_NEWS_TABLES)


def run_migrations_offline():
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    connectable = engine_from_config(
        config.get_section(config.config_ini_section), prefix="sqlalchemy.", poolclass=pool.NullPool
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
